config/routes.rb
Rails.application.routes.draw do

  root controller: 'taco_search', action: :index

  get 'connecting' => 'connecting#index'
  get 'schema' => 'schema#index'
  resources :questions
  resources :coding_challenge, only: [:index]
  resources :taco_search
  post 'search' => 'taco_search#search'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  def output
    conn = ActiveRecord::Base.connection.raw_connection
    table = ::Text::Table.new
    conn.exec(answers.first.answer) do |result|
      table.head = result.fields
      table.rows = result.values
    end
    table.to_s
  end
end

app/models/salsa.rb
class Salsa < ActiveRecord::Base
	belongs_to :store
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :salsas
	has_many :tacos
end

app/models/taco.rb
class Taco < ActiveRecord::Base
	belongs_to :store
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coding_challenge_controller.rb
class CodingChallengeController < ApplicationController
  def index
  end
end

app/controllers/connecting_controller.rb
class ConnectingController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.eager_load(:answers)
  end

end

app/controllers/schema_controller.rb
class SchemaController < ApplicationController
end

app/controllers/taco_search_controller.rb
class TacoSearchController < ApplicationController
	def index
		@tacos = TacoSearch.tacos
		@salsas = TacoSearch.salsas
	end

	def search
		if params[:taco_id] || params[:salsa_id]
			@stores = TacoSearch.search_stores(params[:taco_id],params[:salsa_id])
		else
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connecting_helper.rb
module ConnectingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/schema_helper.rb
module SchemaHelper
end

app/helpers/taco_search_helper.rb
module TacoSearchHelper
end

app/views/coding_challenge/index.html.erb
<h1>TacoCopter Coding Challenge</h1>

<!-- <h2>Using SQL Fiddle</h2> -->

<p>Here in Santa Barbara, we're passionate about our tacos. In fact, we get tacos catered for lunch every Wednesday. When we go out for lunch, though, we want to make sure the shop we go to has the right fillings and sauces to satisfy everyone.</p>

<p>Your mission, should you choose to accept it, is to help us by writing a Rails app that solves this conundrum.</p>

<p>To begin, clone or fork <a href="https://github.com/procore/tacocopter-sql-workshop" target="_blank">this Github repo</a> and create a database which you can seed using <code>bin/rake db:setup</code>. This will generate a database populated with data following <%= link_to 'this schema', :schema %> . Once you're up and running, implement the provided mock to satisfy our ravenous programmers.</p>

<p>Don't worry about making it look beautiful as we're going to be laser-focused on your code. We'll be looking for:</p>

<ul>
  <li>Clean, idiomatic Ruby/Rails code</li>
  <li>Test coverage</li>
  <li>Sane database queries</li>
</ul>

<%= image_tag 'tacocopter_ui_example.png'%>

app/views/connecting/index.html.erb
<h1>Connecting</h1>

<h2>Using SQL Fiddle</h2>

<p>In a new tab, visit <a href='http://sqlfiddle.com'>http://sqlfiddle.com</a></p>

<p>Switch to Postgres 9.3:</p>
<%= image_tag 'switch_to_postgres.png' %>

<p>
In a new tab open <a href="https://raw.githubusercontent.com/bradurani/tacocopter-sql-workshop/master/db/tacocopter.sql"/>https://raw.githubusercontent.com/bradurani/tacocopter-sql-workshop/master/db/tacocopter.sql</a>
</p>

<p>Select the entire contents of this file, copy it and paste it into the schema panel in SQL Fiddle:</p>
<%= image_tag 'paste_sql.png'%>
<p>
press the 'Build Schema' button. You should see a <code>schema ready</code> message. You are now ready to start writting SQL in the "Run SQL" pane.</p>
<br/>
<hr/>
<br/>

app/views/home/index.html.erb
<h1>Tacocopter SQL Training</h1>

<ul>
  <li><%= link_to "Connecting", connecting_path %></li>
  <li><%= link_to "Schema", schema_path %></li>
  <li><%= link_to "Questions", questions_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tacocopter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |q| %>
  <div>
    <span class='q'><%= q.id %>:&nbsp;</span>
    <span class='question'><%= q.question.html_safe %></span>
  </div>
  <div class='output'>
    <pre>
<%= q.output.strip!.html_safe %>
    </pre>
  </div>
  <div class='answer'>
    <button class='show-answer'>Show Answer</button>
    <% q.answers.each do |a| %>
      <div class='answer-content'>
        <%= a.answer.gsub("\n","<br/>").html_safe %>
      </div>
    <% end %>
  </div>
  <hr/>
  <br/>
<% end %>

app/views/schema/index.html.erb
<%= image_tag 'taco-schema.png' %>

app/views/taco_search/index.html.erb
<%= form_tag "/search", method: "post" do %>
<div class="tacos-container row">
	<div class="row">
		<div class="large-6 columns tacos-section">
			<div class="title">Select Taco to Find:</div>
			<% @tacos.each do |taco| %>
				<div>
					<%= check_box_tag('taco_id[]', taco.id) %>
					<%= label_tag('taco_name[]', taco.name) %>
				</div>
			<% end %>
		</div>
	</div>
</div>
<div class="sauces-container row">
	<div class="row">
		<div class="large-6 columns sauces-section">
			<div class="title">Select Sauces to Find:</div>
			<% @salsas.each do |salsa| %>
				<div>
					<%= check_box_tag('salsa_id[]', salsa.id) %>
					<%= label_tag('salsa_id[]', salsa.name) %>
				</div>
			<% end %>
		</div>
	</div>
	<%= submit_tag("Search", class: "button radius search") %>
</div>
<% end %>

app/views/taco_search/search.html.erb
<div class="tacos-container row">
  <div class='row'> 
    <div class='title'> Stores Matching Your Requirements: </div>
    <table>
      <thead>
        <tr>
          <th>Store</th>
          <th>City</th>
        </tr>
      </thead>
      <tbody>
        <% @stores.each do |store| %>
        <tr>
          <td><%= store.name %></td>
          <td><%= store.city_name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>